### ISSUE TITLE
dbxcli version?

### ISSUE THREAD

**Issue by shadiakiki1986** [feklee/dbx-tools#1]
Hello. Your readme says `tested with dbxcli Git release v2.1.1` but then it lists right below it `dbxcli version: 0.1.0`, so I'm confused. Are these tools for v2.1.1 or for 0.1.0?

**Comment by feklee** [comment]
Indeed this is confusing. Thing is that the version reported by `dbxcli version` doesn’t match the tag in Git. I added that information to `README.md`.
